INSERT INTO "PUBLIC"."USERS" VALUES (1, 'me@me.com', 'Me', '$2a$10$e2PfjV5URAM6HcZxD8u9Iui0y/Rm1hcAxz3FUwGWTC7z9k24FG9ge'), (2, 'he@me.com', 'HE', '$2a$10$e2PfjV5URAM6HcZxD8u9Iui0y/Rm1hcAxz3FUwGWTC7z9k24FG9ge');
INSERT INTO "PUBLIC"."ROLES" VALUES (1, 'ROLE_CONSUMER');
INSERT INTO "PUBLIC"."ROLES" VALUES (2, 'ROLE_ADMIN');
INSERT INTO "PUBLIC"."USER_ROLES" VALUES (1, 2);
INSERT INTO "PUBLIC"."USER_ROLES" VALUES (2, 1);
INSERT INTO "PUBLIC"."AUTHORITIES" VALUES (1, 'GET', 'article', 1);
INSERT INTO "PUBLIC"."AUTHORITIES" VALUES (2, 'GET', 'article', 2);
INSERT INTO "PUBLIC"."AUTHORITIES" VALUES (3, 'POST', 'article', 2);
INSERT INTO "PUBLIC"."AUTHORITIES" VALUES (4, 'PUT', 'article', 2);
INSERT INTO "PUBLIC"."AUTHORITIES" VALUES (5, 'DELETE', 'article', 2);

INSERT INTO "PUBLIC"."AUTHORITIES" VALUES (6, 'GET', 'user', 1);
INSERT INTO "PUBLIC"."AUTHORITIES" VALUES (7, 'GET', 'user', 2);
INSERT INTO "PUBLIC"."AUTHORITIES" VALUES (8, 'POST', 'user', 2);
INSERT INTO "PUBLIC"."AUTHORITIES" VALUES (9, 'PUT', 'user', 2);
INSERT INTO "PUBLIC"."AUTHORITIES" VALUES (10, 'DELETE', 'user', 2);